language: node_js
node_js:
  - "stable"
before_install:
  - cd $TRAVIS_BUILD_DIR/.travis
  - openssl aes-256-cbc -K $encrypted_f217180e22ee_key -iv $encrypted_f217180e22ee_iv -in id_rsa.enc -out id_rsa -d
after_success:
  - cd $TRAVIS_BUILD_DIR/.travis
  - deploy.sh
cache:
  yarn: true
  directories:
    - app/node_modules
script:
  - cd $TRAVIS_BUILD_DIR/app
  - yarn install
  - yarn lint
  - yarn test
  - yarn build
  