language: node_js
node_js:
  - "stable"
before_install:
  - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
  # Repo for Yarn
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn lint
  - yarn test
  - yarn build