language: node_js
node_js:
  - "stable"
before_install:
  - cd $TRAVIS_BUILD_DIR/.travis
  - openssl aes-256-cbc -K $encrypted_f217180e22ee_key -iv $encrypted_f217180e22ee_iv -in id_rsa.enc -out id_rsa -d
  - chmod 600 id_rsa
  - mv id_rsa $HOME/.ssh/
  - cat server.pub >> $HOME/.ssh/known_hosts
deploy:
  - provider: script
    script: bash $TRAVIS_BUILD_DIR/.travis/deploy.sh
    on:
      branch: master
cache:
  yarn: true
  directories:
    - app/node_modules
script:
  - cd $TRAVIS_BUILD_DIR/app
  - yarn install
  - yarn lint
  - yarn test
  - yarn build
