language: node_js
node_js:
  - "stable"
before_install:
  - openssl aes-256-cbc -K $encrypted_f217180e22ee_key -iv $encrypted_f217180e22ee_iv -in .travis/id_rsa.enc -out .travis/id_rsa -d
after_success:
  - .travis/deploy.sh
cache:
  yarn: true
  directories:
    - app/node_modules
script:
  - cd app
  - yarn install
  - yarn lint
  - yarn test
  - yarn build
  