import type { Block } from 'payload';

export const Code: Block = {
  slug: 'code',
  interfaceName: 'CodeBlock',
  fields: [
    {
      name: 'language',
      type: 'select',
      defaultValue: 'plaintext',
      required: true,
      options: [
        // Populated from Highlight.js on 04/09/2024
        { label: '(Auto)', value: 'auto' },
        { label: '1C', value: '1c' },
        { label: 'ABNF', value: 'abnf' },
        { label: 'Access Log', value: 'accesslog' },
        { label: 'ActionScript', value: 'actionscript' },
        { label: 'Ada', value: 'ada' },
        { label: 'AngelScript', value: 'angelscript' },
        { label: 'Apache', value: 'apache' },
        { label: 'AppleScript', value: 'applescript' },
        { label: 'Arcade', value: 'arcade' },
        { label: 'Arduino', value: 'arduino' },
        { label: 'ARM Assembly', value: 'armasm' },
        { label: 'AsciiDoc', value: 'asciidoc' },
        { label: 'AspectJ', value: 'aspectj' },
        { label: 'AutoHotkey', value: 'autohotkey' },
        { label: 'AutoIt', value: 'autoit' },
        { label: 'AVR Assembly', value: 'avrasm' },
        { label: 'AWK', value: 'awk' },
        { label: 'Axapta', value: 'axapta' },
        { label: 'Bash', value: 'bash' },
        { label: 'Basic', value: 'basic' },
        { label: 'BNF', value: 'bnf' },
        { label: 'Brainfuck', value: 'brainfuck' },
        { label: 'C', value: 'c' },
        { label: 'C#', value: 'csharp' },
        { label: 'C++', value: 'cpp' },
        { label: 'CAL', value: 'cal' },
        { label: 'Cap’n Proto', value: 'capnproto' },
        { label: 'Ceylon', value: 'ceylon' },
        { label: 'Clean', value: 'clean' },
        { label: 'Clojure', value: 'clojure' },
        { label: 'Clojure REPL', value: 'clojure-repl' },
        { label: 'CMake', value: 'cmake' },
        { label: 'CoffeeScript', value: 'coffeescript' },
        { label: 'Coq', value: 'coq' },
        { label: 'COS', value: 'cos' },
        { label: 'Crmsh', value: 'crmsh' },
        { label: 'Crystal', value: 'crystal' },
        { label: 'CSP', value: 'csp' },
        { label: 'CSS', value: 'css' },
        { label: 'D', value: 'd' },
        { label: 'Dart', value: 'dart' },
        { label: 'Delphi', value: 'delphi' },
        { label: 'Diff', value: 'diff' },
        { label: 'Django', value: 'django' },
        { label: 'DNS', value: 'dns' },
        { label: 'Dockerfile', value: 'dockerfile' },
        { label: 'DOS', value: 'dos' },
        { label: 'Dsconfig', value: 'dsconfig' },
        { label: 'DTS', value: 'dts' },
        { label: 'Dust', value: 'dust' },
        { label: 'EBNF', value: 'ebnf' },
        { label: 'Elixir', value: 'elixir' },
        { label: 'Elm', value: 'elm' },
        { label: 'ERB', value: 'erb' },
        { label: 'Erlang', value: 'erlang' },
        { label: 'Erlang REPL', value: 'erlang-repl' },
        { label: 'Excel', value: 'excel' },
        { label: 'F#', value: 'fsharp' },
        { label: 'FIX', value: 'fix' },
        { label: 'Flix', value: 'flix' },
        { label: 'Fortran', value: 'fortran' },
        { label: 'G-code', value: 'gcode' },
        { label: 'GAMS', value: 'gams' },
        { label: 'Gauss', value: 'gauss' },
        { label: 'Gherkin', value: 'gherkin' },
        { label: 'GLSL', value: 'glsl' },
        { label: 'GML', value: 'gml' },
        { label: 'Go', value: 'go' },
        { label: 'Golo', value: 'golo' },
        { label: 'Gradle', value: 'gradle' },
        { label: 'GraphQL', value: 'graphql' },
        { label: 'Groovy', value: 'groovy' },
        { label: 'Haml', value: 'haml' },
        { label: 'Handlebars', value: 'handlebars' },
        { label: 'Haskell', value: 'haskell' },
        { label: 'Haxe', value: 'haxe' },
        { label: 'HSP', value: 'hsp' },
        { label: 'HTTP', value: 'http' },
        { label: 'Hy', value: 'hy' },
        { label: 'Inform 7', value: 'inform7' },
        { label: 'INI', value: 'ini' },
        { label: 'IRPF90', value: 'irpf90' },
        { label: 'ISBL', value: 'isbl' },
        { label: 'Java', value: 'java' },
        { label: 'JavaScript', value: 'javascript' },
        { label: 'JBoss CLI', value: 'jboss-cli' },
        { label: 'JSON', value: 'json' },
        { label: 'Julia', value: 'julia' },
        { label: 'Julia REPL', value: 'julia-repl' },
        { label: 'Kotlin', value: 'kotlin' },
        { label: 'Lasso', value: 'lasso' },
        { label: 'LaTeX', value: 'latex' },
        { label: 'LDIF', value: 'ldif' },
        { label: 'Leaf', value: 'leaf' },
        { label: 'LESS', value: 'less' },
        { label: 'Lisp', value: 'lisp' },
        { label: 'LiveCode Server', value: 'livecodeserver' },
        { label: 'LiveScript', value: 'livescript' },
        { label: 'LLVM', value: 'llvm' },
        { label: 'LSL', value: 'lsl' },
        { label: 'Lua', value: 'lua' },
        { label: 'Makefile', value: 'makefile' },
        { label: 'Markdown', value: 'markdown' },
        { label: 'Mathematica', value: 'mathematica' },
        { label: 'MATLAB', value: 'matlab' },
        { label: 'Maxima', value: 'maxima' },
        { label: 'MEL', value: 'mel' },
        { label: 'Mercury', value: 'mercury' },
        { label: 'MIPS Assembly', value: 'mipsasm' },
        { label: 'Mizar', value: 'mizar' },
        { label: 'Mojolicious', value: 'mojolicious' },
        { label: 'Monkey', value: 'monkey' },
        { label: 'MoonScript', value: 'moonscript' },
        { label: 'N1QL', value: 'n1ql' },
        { label: 'NestedText', value: 'nestedtext' },
        { label: 'Nginx', value: 'nginx' },
        { label: 'Nim', value: 'nim' },
        { label: 'Nix', value: 'nix' },
        { label: 'Node REPL', value: 'node-repl' },
        { label: 'NSIS', value: 'nsis' },
        { label: 'Objective-C', value: 'objectivec' },
        { label: 'OCaml', value: 'ocaml' },
        { label: 'OpenSCAD', value: 'openscad' },
        { label: 'Oxygene', value: 'oxygene' },
        { label: 'Parser3', value: 'parser3' },
        { label: 'Perl', value: 'perl' },
        { label: 'PF', value: 'pf' },
        { label: 'PHP', value: 'php' },
        { label: 'PHP Template', value: 'php-template' },
        { label: 'Plain Text', value: 'plaintext' },
        { label: 'Pony', value: 'pony' },
        { label: 'PostgreSQL', value: 'pgsql' },
        { label: 'PowerShell', value: 'powershell' },
        { label: 'Processing', value: 'processing' },
        { label: 'Profile', value: 'profile' },
        { label: 'Prolog', value: 'prolog' },
        { label: 'Properties', value: 'properties' },
        { label: 'Protobuf', value: 'protobuf' },
        { label: 'Puppet', value: 'puppet' },
        { label: 'PureBasic', value: 'purebasic' },
        { label: 'Python', value: 'python' },
        { label: 'Python REPL', value: 'python-repl' },
        { label: 'Q', value: 'q' },
        { label: 'QML', value: 'qml' },
        { label: 'R', value: 'r' },
        { label: 'ReasonML', value: 'reasonml' },
        { label: 'RIB', value: 'rib' },
        { label: 'Roboconf', value: 'roboconf' },
        { label: 'RouterOS', value: 'routeros' },
        { label: 'RSL', value: 'rsl' },
        { label: 'Ruby', value: 'ruby' },
        { label: 'Rules Language', value: 'ruleslanguage' },
        { label: 'Rust', value: 'rust' },
        { label: 'SAS', value: 'sas' },
        { label: 'Scala', value: 'scala' },
        { label: 'Scheme', value: 'scheme' },
        { label: 'Scilab', value: 'scilab' },
        { label: 'SCSS', value: 'scss' },
        { label: 'Shell', value: 'shell' },
        { label: 'Smali', value: 'smali' },
        { label: 'Smalltalk', value: 'smalltalk' },
        { label: 'SML', value: 'sml' },
        { label: 'SQF', value: 'sqf' },
        { label: 'SQL', value: 'sql' },
        { label: 'Stan', value: 'stan' },
        { label: 'Stata', value: 'stata' },
        { label: 'STEP21', value: 'step21' },
        { label: 'Stylus', value: 'stylus' },
        { label: 'SubUnit', value: 'subunit' },
        { label: 'Swift', value: 'swift' },
        { label: 'TaggerScript', value: 'taggerscript' },
        { label: 'TAP', value: 'tap' },
        { label: 'Tcl', value: 'tcl' },
        { label: 'Thrift', value: 'thrift' },
        { label: 'TP', value: 'tp' },
        { label: 'Twig', value: 'twig' },
        { label: 'TypeScript', value: 'typescript' },
        { label: 'Vala', value: 'vala' },
        { label: 'VB.NET', value: 'vbnet' },
        { label: 'VBScript', value: 'vbscript' },
        { label: 'VBScript (HTML)', value: 'vbscript-html' },
        { label: 'Verilog', value: 'verilog' },
        { label: 'VHDL', value: 'vhdl' },
        { label: 'Vim', value: 'vim' },
        { label: 'WebAssembly', value: 'wasm' },
        { label: 'Wren', value: 'wren' },
        { label: 'x86 Assembly', value: 'x86asm' },
        { label: 'XL', value: 'xl' },
        { label: 'XML', value: 'xml' },
        { label: 'XQuery', value: 'xquery' },
        { label: 'YAML', value: 'yaml' },
        { label: 'Zephir', value: 'zephir' },
      ],
    },
    {
      name: 'code',
      type: 'code',
      label: false,
      required: true,
    },
  ],
};
