name: Build, Test and Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_test_app:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      working-directory: ./app
      run: yarn install
    - name: Lint
      working-directory: ./app
      run: yarn lint
    - name: Test
      working-directory: ./app
      run: yarn test
    - name: Build
      working-directory: ./app
      run: yarn build
      
  build_test_server:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      working-directory: ./server
      run: yarn install
    - name: Lint
      working-directory: ./server
      run: yarn lint
    - name: Test
      working-directory: ./server
      run: yarn test
    - name: Build
      working-directory: ./server
      run: yarn build

  deploy:
    runs-on: ubuntu-latest
    needs: [build_test_app, build_test_server]
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: Deploy App (via webhook)
        uses: distributhor/workflow-webhook@v2
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          data: '{
            "DOCKER_COMPOSE_PROJECT_NAME": "${{ vars.APP_DOCKER_COMPOSE_PROJECT_NAME }}",
            "GIT_REPOSITORY_NAME": "${{ vars.GIT_REPOSITORY_NAME }}"
          }'

      - name: Deploy Server (via webhook)
        uses: distributhor/workflow-webhook@v2
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          data: '{
            "DOCKER_COMPOSE_PROJECT_NAME": "${{ vars.SERVER_DOCKER_COMPOSE_PROJECT_NAME }}",
            "GIT_REPOSITORY_NAME": "${{ vars.GIT_REPOSITORY_NAME }}"
          }'
